from django.db import models


# Create your models here.
class Tasks(models.Model):
    task_id = models.CharField(max_length=200) # generated by celery so random
    job_name = models.CharField(max_length=200) # user input
    dna_string = models.TextField(max_length=1000) # user input
    dna_result = models.TextField(max_length=2000) # result of find_protein function

    def __str__(self):
        return f"{self.task_id} {self.job_name}"
